# fly.toml app configuration file generated for real-nurture-backend on 2025-05-17T18:35:33-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'real-nurture-backend'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '3000'
  HOST = '0.0.0.0'

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0

  [http_service.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

  [[http_service.checks]]
    interval = "10s"
    grace_period = "30s"
    method = "get"
    path = "/"
    protocol = "http"
    timeout = "5s"
